import React from 'react';
import {NativeStackScreenProps} from '@react-navigation/native-stack';
import {StatusBar, StyleSheet, Text, View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useOrders} from '../context/OrdersContext';
import {RootStackParamList} from '../navigation/navigationTypes';
import PlaceholderScreen from './PlaceholderScreen';
type Props = NativeStackScreenProps<RootStackParamList, 'OrderTracking'>;
function OrderTrackingScreen({route}: Props) {const {findOrder} = useOrders(); const order = findOrder(route.params.orderId); if (!order) return <PlaceholderScreen eyebrow="NOT FOUND" title="Tracking unavailable" description="This order could not be found." />; const steps = ['Confirmed', 'Packed', 'Shipped', 'Out for delivery', 'Delivered']; const current = order.status === 'Delivered' ? 4 : order.status === 'Shipped' ? 2 : 0; return <SafeAreaView edges={['bottom']} style={styles.safeArea}><StatusBar barStyle="light-content" backgroundColor="#101820" /><View style={styles.content}><Text style={styles.eyebrow}>LIVE ORDER STATUS</Text><Text style={styles.title}>{order.id}</Text><Text style={styles.copy}>{order.status === 'Cancelled' ? 'This order was cancelled.' : 'Estimated arrival in 3–5 business days.'}</Text><View style={styles.card}>{steps.map((step, index) => <View key={step} style={styles.step}><View style={styles.markerColumn}><View style={[styles.dot, index <= current && order.status !== 'Cancelled' && styles.activeDot]} />{index < steps.length - 1 && <View style={[styles.line, index < current && styles.activeLine]} />}</View><View><Text style={[styles.stepTitle, index <= current && styles.activeText]}>{step}</Text><Text style={styles.stepCopy}>{index <= current ? 'Completed' : 'Pending'}</Text></View></View>)}</View></View></SafeAreaView>;}
const styles = StyleSheet.create({safeArea: {flex: 1, backgroundColor: '#F5F6F8'}, content: {padding: 18}, eyebrow: {color: '#D94F04', fontSize: 9, fontWeight: '900', letterSpacing: 1.3}, title: {color: '#101820', fontSize: 25, fontWeight: '900', marginTop: 5}, copy: {color: '#78838B', fontSize: 10, marginTop: 5, marginBottom: 18}, card: {backgroundColor: '#FFFFFF', borderRadius: 12, padding: 18}, step: {height: 68, flexDirection: 'row'}, markerColumn: {width: 32, alignItems: 'center'}, dot: {width: 16, height: 16, borderRadius: 8, backgroundColor: '#D6DCE0'}, activeDot: {backgroundColor: '#23835C'}, line: {width: 2, flex: 1, backgroundColor: '#D6DCE0'}, activeLine: {backgroundColor: '#23835C'}, stepTitle: {color: '#89939A', fontSize: 11, fontWeight: '800'}, activeText: {color: '#34414A'}, stepCopy: {color: '#9AA2A8', fontSize: 8, marginTop: 4}});
export default OrderTrackingScreen;
