import React, {useState} from 'react';
import {NativeStackScreenProps} from '@react-navigation/native-stack';
import {Alert, Pressable, ScrollView, StatusBar, StyleSheet, Text, View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {useOrders} from '../context/OrdersContext';
import {RootStackParamList} from '../navigation/navigationTypes';

type Props = NativeStackScreenProps<RootStackParamList, 'Returns'>;
const reasons = ['Damaged or defective', 'Wrong item received', 'No longer needed', 'Other'];
function ReturnsScreen({navigation, route}: Props) {const {orders, requestReturn} = useOrders(); const [orderId, setOrderId] = useState(route.params?.orderId ?? ''); const [reason, setReason] = useState(''); const eligible = orders.filter(order => order.status !== 'Return requested'); const submit = () => {if (!orderId || !reason) {Alert.alert('Select an order and return reason.'); return;} requestReturn(orderId, reason); Alert.alert('Return requested', 'We’ll notify you with pickup instructions.', [{text: 'View order', onPress: () => navigation.replace('OrderDetails', {orderId})}]);}; return <SafeAreaView edges={['bottom']} style={styles.safeArea}><StatusBar barStyle="light-content" backgroundColor="#101820" /><ScrollView contentContainerStyle={styles.content}><Text style={styles.eyebrow}>RETURNS CENTRE</Text><Text style={styles.title}>Return an item</Text><Text style={styles.copy}>Choose an eligible order and tell us what happened.</Text><Text style={styles.heading}>Select order</Text>{eligible.length === 0 ? <View style={styles.empty}><Text style={styles.emptyTitle}>No eligible orders</Text><Text style={styles.copy}>Orders already under return won’t appear here.</Text></View> : eligible.map(order => <Pressable key={order.id} onPress={() => setOrderId(order.id)} style={[styles.option, orderId === order.id && styles.selected]}><View style={[styles.radio, orderId === order.id && styles.selectedRadio]} /><View><Text style={styles.optionTitle}>{order.id}</Text><Text style={styles.optionCopy}>{order.items.length} products · ₹{order.total.toLocaleString('en-IN')}</Text></View></Pressable>)}<Text style={styles.heading}>Reason for return</Text>{reasons.map(item => <Pressable key={item} onPress={() => setReason(item)} style={[styles.option, reason === item && styles.selected]}><View style={[styles.radio, reason === item && styles.selectedRadio]} /><Text style={styles.optionTitle}>{item}</Text></Pressable>)}{eligible.length > 0 && <Pressable onPress={submit} style={styles.button}><Text style={styles.buttonText}>Submit return request</Text></Pressable>}</ScrollView></SafeAreaView>;}
const styles = StyleSheet.create({safeArea: {flex: 1, backgroundColor: '#F5F6F8'}, content: {padding: 16, paddingBottom: 30}, eyebrow: {color: '#D94F04', fontSize: 9, fontWeight: '900', letterSpacing: 1.3}, title: {color: '#101820', fontSize: 26, fontWeight: '900', marginTop: 5}, copy: {color: '#78838B', fontSize: 10, lineHeight: 16, marginTop: 5}, heading: {color: '#34414A', fontSize: 12, fontWeight: '900', marginTop: 22, marginBottom: 9}, option: {minHeight: 58, flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#D9DEE1', borderRadius: 10, padding: 12, marginBottom: 8}, selected: {borderColor: '#E85D04', backgroundColor: '#FFF8F4'}, radio: {width: 18, height: 18, borderRadius: 9, borderWidth: 2, borderColor: '#B6BFC5', marginRight: 11}, selectedRadio: {borderWidth: 5, borderColor: '#E85D04'}, optionTitle: {color: '#35424B', fontSize: 10, fontWeight: '800'}, optionCopy: {color: '#808A91', fontSize: 8, marginTop: 4}, button: {height: 49, borderRadius: 9, backgroundColor: '#FFB000', alignItems: 'center', justifyContent: 'center', marginTop: 22}, buttonText: {color: '#101820', fontSize: 11, fontWeight: '900'}, empty: {backgroundColor: '#FFFFFF', borderRadius: 10, padding: 18}, emptyTitle: {color: '#34414A', fontSize: 12, fontWeight: '900'}});
export default ReturnsScreen;
