import { Router } from 'express';
import { authRouter } from '../modules/auth/auth.routes.js';
import { catalogueRouter } from '../modules/catalogue/catalogue.routes.js';
import { accountRouter } from '../modules/account/account.routes.js';
import { addressRouter } from '../modules/addresses/address.routes.js';
import { cartRouter } from '../modules/cart/cart.routes.js';
import { wishlistRouter } from '../modules/wishlist/wishlist.routes.js';
import { orderRouter } from '../modules/orders/order.routes.js';
import { fulfilmentRouter } from '../modules/fulfilment/fulfilment.routes.js';
import { notificationRouter } from '../modules/notifications/notification.routes.js';
import { supportRouter } from '../modules/support/support.routes.js';
import { adminRouter } from '../modules/admin/admin.routes.js';
import { paymentRouter } from '../modules/payments/payment.routes.js';

export const apiRouter = Router();
apiRouter.use('/auth', authRouter);
apiRouter.use('/account', accountRouter);
apiRouter.use('/addresses', addressRouter);
apiRouter.use('/cart', cartRouter);
apiRouter.use('/wishlist', wishlistRouter);
apiRouter.use('/orders', orderRouter);
apiRouter.use('/fulfilment', fulfilmentRouter);
apiRouter.use('/notifications', notificationRouter);
apiRouter.use('/support', supportRouter);
apiRouter.use('/admin', adminRouter);
apiRouter.use('/payments', paymentRouter);
apiRouter.use(catalogueRouter);
